<?php

/**
 * HTTP verification for LOCAL SIMULATION staging release.
 * Usage: php database/scripts/staging-http-verify.php [baseUrl]
 */

$base = rtrim($argv[1] ?? 'http://127.0.0.1:8000', '/');

$paths = [
    '/blog',
    '/blog/glass-partitions-open-plan',
    '/blog/pvd-coating-explained',
    '/blog/corten-steel-modern-facades',
    '/sitemap.xml',
];

$checks = [];

foreach ($paths as $path) {
    $url = $base.$path;
    $ctx = stream_context_create(['http' => ['ignore_errors' => true, 'timeout' => 15]]);
    $body = @file_get_contents($url, false, $ctx);
    $status = 0;
    if (isset($http_response_header[0]) && preg_match('/\s(\d{3})\s/', $http_response_header[0], $m)) {
        $status = (int) $m[1];
    }
    $checks[] = ['path' => $path, 'status' => $status, 'bytes' => strlen($body ?: '')];
    echo sprintf("%s %s (%d bytes)\n", $path, $status === 200 ? 'OK' : "HTTP {$status}", strlen($body ?: ''));
}

echo "\n=== Pillar page content checks ===\n";
foreach ([
    'glass-partitions-open-plan',
    'pvd-coating-explained',
    'corten-steel-modern-facades',
] as $slug) {
    $url = $base.'/blog/'.$slug;
    $html = @file_get_contents($url, false, stream_context_create(['http' => ['timeout' => 15]]));
    if (! $html) {
        echo "  {$slug}: fetch failed\n";
        continue;
    }
    $hasPicture = str_contains($html, '<picture') && str_contains($html, '.webp');
    $hasSchema = str_contains($html, 'application/ld+json');
    $hasOgAbsolute = (bool) preg_match('#property="og:image"\s+content="https?://#', $html);
    $hasAiTrace = (bool) preg_match('/\b(as an ai|chatgpt|generated by ai)\b/i', $html);
    echo "  {$slug}: picture+webp=".($hasPicture ? 'yes' : 'NO')
        .', schema='.($hasSchema ? 'yes' : 'NO')
        .', og absolute='.($hasOgAbsolute ? 'yes' : 'NO')
        .', ai trace='.($hasAiTrace ? 'FOUND' : 'none')."\n";
}

echo "\n=== Blog index pillar visibility ===\n";
$index = @file_get_contents($base.'/blog', false, stream_context_create(['http' => ['timeout' => 15]]));
if ($index) {
    preg_match_all('#/blog/([a-z0-9-]+)#', $index, $m);
    $links = array_unique($m[1] ?? []);
    echo '  Unique article slugs linked on /blog: '.count($links)."\n";
    foreach (['glass-partitions-open-plan', 'pvd-coating-explained', 'corten-steel-modern-facades'] as $slug) {
        echo '    '.$slug.': '.(in_array($slug, $links, true) ? 'listed' : 'MISSING')."\n";
    }
}
