<?php

return [
    'countries' => [
        'India',
        'United States',
        'United Kingdom',
        'Canada',
        'Australia',
        'United Arab Emirates',
        'Singapore',
        'Germany',
        'France',
        'Italy',
        'Spain',
        'Netherlands',
        'Switzerland',
        'Belgium',
        'Sweden',
        'Norway',
        'Denmark',
        'Japan',
        'South Korea',
        'China',
        'Hong Kong',
        'Malaysia',
        'Thailand',
        'Indonesia',
        'Philippines',
        'Saudi Arabia',
        'Qatar',
        'Kuwait',
        'Bahrain',
        'Oman',
        'South Africa',
        'New Zealand',
        'Brazil',
        'Mexico',
        'Portugal',
        'Ireland',
        'Austria',
        'Turkey',
        'Israel',
        'Other',
    ],

    'india_states' => [
        'Andaman and Nicobar Islands',
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chandigarh',
        'Chhattisgarh',
        'Dadra and Nagar Haveli and Daman and Diu',
        'Delhi',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jammu and Kashmir',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Ladakh',
        'Lakshadweep',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Puducherry',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal',
    ],

    'address_types' => [
        'home' => 'Home',
        'work' => 'Work',
        'other' => 'Other',
    ],

    'pin_lookup_statuses' => [
        'format_valid',
        'lookup_verified',
        'manual_review',
    ],

    'payment_unavailable_message' => 'Online payment is currently unavailable. Please contact Vyomika Atelier to complete your order.',
];
