<?php

/**
 * Checkout collection landing pages (gallery layout like mirror frames).
 */
return [
    'coffee-tables' => [
        'meta_title' => 'Coffee Tables Collection | Vyomika Atelier',
        'meta_description' => 'PVD metal coffee tables with glass, marble and fluted bases — fixed prices with Pan-India delivery from Vyomika Atelier.',
        'hero' => [
            'hero_layout' => 'compact',
            'eyebrow' => 'PVD Metal Furniture',
            'title_line1' => 'Designer',
            'title_accent' => 'Metal',
            'title_line2' => 'Coffee Tables',
            'tagline' => 'Crafted to be',
            'tagline_accent' => 'the centerpiece.',
            'highlights' => [
                'Sculptural design',
                'Premium finishes',
                'Timeless elegance',
                'Made for luxury spaces',
            ],
            'footer_tagline' => 'Bold forms.',
            'footer_tagline_accent' => 'Built to last.',
            'cta_primary' => ['label' => 'Browse Designs', 'href' => '#collection-gallery'],
            'cta_secondary' => ['label' => 'Browse All Shop', 'href' => '/shop'],
            'image' => 'images/shop-heroes/coffee-tables-hero.png',
        ],
        'intro' => [
            'title' => 'Metal Coffee Tables, Built to Anchor Your Space',
            'body' => 'Each coffee table is fabricated in our Delhi studio from grade 304/316 stainless with PVD coating — paired with toughened glass or natural stone tops for residential and commercial interiors.',
        ],
        'gallery_title' => 'Coffee Table Designs',
    ],
    'corner-tables' => [
        'meta_title' => 'Corner Tables Collection | Vyomika Atelier',
        'meta_description' => 'PVD corner and side tables with marble and glass tops — fixed prices with Pan-India delivery from Vyomika Atelier.',
        'hero' => [
            'hero_layout' => 'compact',
            'eyebrow' => 'PVD Metal Furniture',
            'title_line1' => 'Designer',
            'title_accent' => 'Metal',
            'title_line2' => 'Corner Tables',
            'tagline' => 'Sculptural. Functional.',
            'tagline_accent' => 'Uniquely yours.',
            'highlights' => [
                'Handcrafted excellence',
                'Premium metal finishes',
                'Durable & timeless',
                'Made to stand out',
            ],
            'footer_tagline' => 'Bold designs.',
            'footer_tagline_accent' => 'Timeless spaces.',
            'cta_primary' => ['label' => 'Browse Designs', 'href' => '#collection-gallery'],
            'cta_secondary' => ['label' => 'Browse All Shop', 'href' => '/shop'],
            'image' => 'images/shop-heroes/corner-tables-hero.png',
        ],
        'intro' => [
            'title' => 'Corner Tables That Fill the Gap Beautifully',
            'body' => 'Designed for tight footprints without compromising presence — PVD frames with stone or glass tops, finished for humid climates and daily use.',
        ],
        'gallery_title' => 'Corner Table Designs',
    ],
    'glass-tables' => [
        'meta_title' => 'Glass Tables Collection | Vyomika Atelier',
        'meta_description' => 'PVD-framed glass side and accent tables — fixed prices with Pan-India delivery from Vyomika Atelier.',
        'hero' => [
            'hero_layout' => 'compact',
            'eyebrow' => 'PVD Metal Furniture',
            'title_line1' => 'Designer',
            'title_accent' => 'Glass',
            'title_line2' => 'Tables',
            'tagline' => 'Light. Elegant.',
            'tagline_accent' => 'Engineered to last.',
            'highlights' => [
                'Toughened glass tops',
                'Slim PVD frames',
                'Studio fabrication',
                'Pan-India delivery',
            ],
            'footer_tagline' => 'Floating surfaces.',
            'footer_tagline_accent' => 'Lasting presence.',
            'cta_primary' => ['label' => 'Browse Designs', 'href' => '#collection-gallery'],
            'cta_secondary' => ['label' => 'Browse All Shop', 'href' => '/shop'],
            'image' => 'images/shop-heroes/glass-tables-hero.png',
        ],
        'intro' => [
            'title' => 'Glass & Metal, Engineered for Light',
            'body' => 'Floating glass surfaces on precision-welded PVD frames — ideal for lounges, hotel rooms and retail display vignettes.',
        ],
        'gallery_title' => 'Glass Table Designs',
    ],
    'door-handles' => [
        'meta_title' => 'Door Handles Collection | Vyomika Atelier',
        'meta_description' => 'PVD door pulls and entrance handles in champagne, rose gold and matte black — Pan-India delivery from Vyomika Atelier.',
        'hero' => [
            'hero_layout' => 'compact',
            'eyebrow' => 'Architectural Hardware',
            'title_line1' => 'Designer',
            'title_accent' => 'Door Handles',
            'tagline' => 'Architectural pulls.',
            'tagline_accent' => 'Premium finishes.',
            'highlights' => [
                'Grade 304/316 stainless',
                'Brushed & mirror PVD',
                'Studio fabrication',
                'Pan-India delivery',
            ],
            'footer_tagline' => 'Every entrance.',
            'footer_tagline_accent' => 'Elevated.',
            'cta_primary' => ['label' => 'Browse Designs', 'href' => '#collection-gallery'],
            'cta_secondary' => ['label' => 'Browse All Shop', 'href' => '/shop'],
            'image' => 'images/shop-heroes/door-handles-hero.png',
        ],
        'intro' => [
            'title' => 'Hardware That Completes the Entrance',
            'body' => 'Pull handles and entrance hardware fabricated to match your door systems — PVD coated for scratch resistance and lasting colour depth.',
        ],
        'gallery_title' => 'Door Handle Designs',
    ],
    'bespoke-metal-furniture' => [
        'meta_title' => 'Bespoke Metal Furniture | Vyomika Atelier',
        'meta_description' => 'Bespoke PVD metal furniture — coffee tables, corner tables, glass tables and consoles — fabricated to order from Vyomika Atelier.',
        'category_slugs' => ['bespoke-metal-furniture'],
        'hero' => [
            'hero_layout' => 'compact',
            'eyebrow' => 'PVD Partitions & Custom Metal Furniture',
            'title_line1' => 'Luxury in Every',
            'title_accent' => 'Detail',
            'title_line2' => 'Metal Furniture',
            'tagline' => 'Bespoke partitions. Timeless furniture.',
            'tagline_accent' => 'Exceptional spaces.',
            'highlights' => [
                'Premium PVD finish',
                'Custom design',
                'Luxury that lasts',
            ],
            'footer_tagline' => 'Crafting elegance.',
            'footer_tagline_accent' => 'Defining spaces.',
            'cta_primary' => ['label' => 'Browse Designs', 'href' => '#collection-gallery'],
            'cta_secondary' => ['label' => 'Request Quote', 'href' => '/custom-order'],
            'image' => 'images/shop-heroes/bespoke-metal-furniture-hero.png',
        ],
        'intro' => [
            'title' => 'Metal Furniture, Built to Your Specification',
            'body' => 'Each piece is fabricated in our Delhi studio from grade 304/316 stainless with PVD coating — paired with toughened glass, marble, or natural stone tops.',
        ],
        'gallery_title' => 'Furniture Designs',
    ],
];
